version: '3.8'

services:
  app:
    build: .
    container_name: laravel-app
    volumes:
      - .:/var/www
    working_dir: /var/www
    ports:
      - "8000:8000"
    environment:
      # ใช้ Environment Variables จากไฟล์ .env โดยตรง
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}